allowBuilds:
  dtrace-provider: true
  protobufjs: false
overrides:
  undici: 6.28.0
  nanoid: 3.3.18
minimumReleaseAgeExclude:
  - '@expo/cli@56.1.24'
  - '@expo/config-plugins@56.0.15'
  - '@expo/prebuild-config@56.0.22'
  - '@expo/router-server@56.0.18'
  - expo-asset@56.0.23
  - expo-constants@56.0.24
  - expo-file-system@56.0.10
  - expo-modules-autolinking@56.0.22
  - expo-modules-core@56.0.24
  - expo-server@56.0.6
  - expo@56.0.20
  - expo-auth-session@56.0.17
  - expo-build-properties@56.0.26
  - expo-dev-client@56.0.25
  - expo-dev-launcher@56.0.26
  - expo-dev-menu@56.0.22
  - expo-image-manipulator@56.0.25
  - expo-image-picker@56.0.24
  - expo-linking@56.0.17
  - expo-notifications@56.0.24
  - expo-sharing@56.0.25
